version: '3.8'

services:
  test-apache-server:
    # image: "ghcr.io/eikonproject/apache_dev_server:main"
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./budget-website/htdocs:/home/htdocs
    ports:
      - 8901:8889
